In [2]:
import numpy as np


In [3]:
class Graph():
    def __init__(self, vertices):
        self.V = vertices
        self.graph = [[0 for column in range(vertices)]
                      for row in range(vertices)]
        
    
    def printSolution(self, dist, par):
        print("Vertex \t Distance from Source \t Parent")
        for node in range(self.V):
            print(node , "\t\t", dist[node], "\t\t", par[node])
    
    def pickMinVertic(self, dist):
        min = np.inf
        for u in self.L:
            if dist[u] < min:
                min = dist[u]
                min_index = u
        return min_index
    
    def dijkstra(self, src):
            dist = [np.inf] * self.V
            dist[src] = 0
            par = [False] * self.V
            self.L = [src]
            print(self.graph)
            while(len(self.L) != 0):
                u = self.pickMinVertic(dist)
                for v in range(self.V):
                    if(self.graph[u][v]!=0):
                        self.L.append(v)
                self.L.remove(u)
                for v in self.L:
                    if(self.graph[u][v] != 0 and dist[v] > dist[u] + self.graph[u][v]):
                        dist[v] = dist[u] + self.graph[u][v]
                        par[v] = u
            self.printSolution(dist, par)


In [4]:
adj = np.loadtxt("graph_directed.txt",delimiter=',')
g = Graph(len(adj))
g.graph = adj
src = int(input("Enter the start vertex(# start from 0):"))
g.dijkstra(src)

Enter the start vertex(# start from 0):2
[[0. 2. 4. 0. 0. 0.]
 [0. 0. 1. 2. 2. 0.]
 [0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 3.]
 [0. 0. 0. 3. 0. 2.]
 [0. 0. 0. 0. 0. 0.]]
Vertex 	 Distance from Source 	 Parent
0 		 inf 		 False
1 		 inf 		 False
2 		 0 		 False
3 		 6.0 		 4
4 		 3.0 		 2
5 		 5.0 		 4
